In [1]:
import sys
sys.path.insert(0, "/Users/riestern/Development/Repositories/deep_learning_lab_course")

import numpy as np
import nn

# CNNs on MNIST
In the third part of the exercise we will now apply CNNs to MNIST.

First, take a look at the neural network code I placed into the nn package in this repository. It should look familiar as it is mainly the code you used in the last exercise. One thing that I added is a prototyped implementation of convolution and pooling. You will find these in nn/conv/layers.py.

After you have completed exercises 2 a) and 2 b) you should go into that file, and implement the missing pieces, which will essentially be the conv and pool functions you have already written as well as their backward pass (which might be a bit more tricky). 

Once you implemented those, come back here and make sure the following example works.

First, let us do gradient checking using your conv and pooling layers.

In [10]:
input_shape = (5, 1, 28, 28)
n_labels = 6
layers = [nn.InputLayer(input_shape)]

layers.append(nn.Conv(
                layers[-1],
                n_feats=2,
                filter_shape=(3,3),
                init_stddev=0.01,
                activation_fun=nn.Activation('relu'),
))
layers.append(nn.Pool(layers[-1]))
layers.append(nn.Flatten(layers[-1]))
layers.append(nn.FullyConnectedLayer(
                layers[-1],
                num_units=6,
                init_stddev=0.1,
                activation_fun=None
))
layers.append(nn.SoftmaxOutput(layers[-1]))
net = nn.NeuralNetwork(layers)

In [11]:
# create random data
X = np.random.normal(size=input_shape)
Y = np.zeros((input_shape[0], n_labels))
for i in range(Y.shape[0]):
    idx = np.random.randint(n_labels)
    Y[i, idx] = 1.

In [12]:
# perform gradient checking, this should go through if you implemented everything correctly!
net.check_gradients(X, Y)

checking gradient for layer 1
diff 8.93e-01


AssertionError: 

# Train on mnist
Finally, figure out a reasonable network architecture and train it on MNIST.

In [6]:
# you can load the mnist data as 
data = nn.data.mnist()

... downloading MNIST from the web
... loading data
... done loading data


In [4]:
import sys
sys.path.insert(0, "/Users/riestern/Development/Repositories/deep_learning_lab_course")
import numpy as np
import nn

input_shape = (1, 3, 5, 5)
layers = [nn.InputLayer(input_shape)]
conv_layer = nn.Conv(
                layers[-1],
                n_feats=2,
                filter_shape=(3,3),
                init_stddev=0.01,
                activation_fun=None)
layers.append(conv_layer)
layers.append(nn.LinearOutput(layers[-1]))

example = np.array([[[[2,2,2,2,1],[1,1,1,1,0],[0,1,0,1,2],[2,2,0,2,0],[0,2,1,0,1]],[[0,0,1,0,0],[0,1,2,1,1],[0,0,0,2,1],[2,2,0,2,0],[1,1,0,0,0]],[[0,1,0,0,0],[2,0,1,1,2],[0,0,0,0,0],[2,2,1,1,1],[1,2,1,0,1]]]])
print("Input shape: " + str(example.shape))

w_0_0 = np.array([[0,1,-1],[-1,-1,0],[1,-1,1]])
w_0_1 = np.array([[-1,0,0],[-1,-1,1],[0,0,-1]])
w_0_2 = np.array([[1,0,-1],[1,0,0],[1,1,-1]])
b_0 = 1

w_1_0 = np.array([[-1,-1,0],[0,-1,0],[-1,0,-1]])
w_1_1 = np.array([[0,-1,1],[-1,0,0],[-1,-1,-1]])
w_1_2 = np.array([[0,1,1],[-1,1,1],[-1,0,0]])
b_1 = 0

conv_layer.W = np.array([[w_0_0,w_1_0],[w_0_1,w_1_1],[w_0_2,w_1_2]])
conv_layer.b = np.array([b_0, b_1])
print("Weight shape: " + str(conv_layer.W.shape))


net = nn.NeuralNetwork(layers)
output = net.predict(example)
print("Output shape: " + str(output.shape))
print("Output: \n" + str(output))

Input shape: (1, 3, 5, 5)
Weight shape: (3, 2, 3, 3)
[[[[0 0 0 0 0 0 0]
   [0 2 2 2 2 1 0]
   [0 1 1 1 1 0 0]
   [0 0 1 0 1 2 0]
   [0 2 2 0 2 0 0]
   [0 0 2 1 0 1 0]
   [0 0 0 0 0 0 0]]

  [[0 0 0 0 0 0 0]
   [0 0 0 1 0 0 0]
   [0 0 1 2 1 1 0]
   [0 0 0 0 2 1 0]
   [0 2 2 0 2 0 0]
   [0 1 1 0 0 0 0]
   [0 0 0 0 0 0 0]]

  [[0 0 0 0 0 0 0]
   [0 0 1 0 0 0 0]
   [0 2 0 1 1 2 0]
   [0 0 0 0 0 0 0]
   [0 2 2 1 1 1 0]
   [0 1 2 1 0 1 0]
   [0 0 0 0 0 0 0]]]]
Output shape: (1, 2, 5, 5)
Output: 
[[[[  0.  -2.  -3.  -5.   2.]
   [  1.   1.  -2.  -2.  -1.]
   [ -1.   4.   4.  -4.  -1.]
   [ -2.  -3.   4.  -1.  -2.]
   [ -1.  -1.  -4.   3.  -1.]]

  [[ -3.  -8.  -9.  -9.  -5.]
   [ -1.  -4.  -9. -10.  -7.]
   [ -4.  -9. -11.  -3.  -9.]
   [ -2.  -8.  -6.  -6.  -6.]
   [  5.  -4.  -1.  -2.  -1.]]]]
